module.exports = {
  titleOptions: {
    titles: [
      `I'm here to help!`,
      `Help is on the way.`,
      `I've come across this issue before...`,
      `I have a green thumb!`,
      `Let's get you squared away.`,
      `Don't worry, we'll save your plant!`,
      `Don't toss it just yet!`,
      `Captain planet here to help.`,
      `Be careful not to over water.`,
      `We can fix this!`,
      `You are NOT a plant murderer!`,
      `Don't be so hard on yourself!`,
      `Taking care of plants is hard...`,
      `Here to help.`,
      `Your plant will be just like new.`,
    ],
  },
  answerParts: {
    partOne: [
      `First thing you'll want to do is assess the root system.`,
      `How long have you had the plant for?`,
      `You'll want to start by closely monitoring how much water it is getting.`,
      `You'll want to start by closely monitoring how much sun it is getting.`,
      `You'll want to start by checking the ph level of your plants soil.`,
      `You're not a terrible plant parent, everyone has issues now and then.`,
      `I have some advice for you, but it may be hard to hear.`,
      `Does this plant differ a lot from the ones you're used to having?`,
      `A green thumb takes time to develop.`,
      `You'll get through this; I promise!`,
      `Oh, that's not that bad.`,
      `I actually did a little bit of research and here's what I found...`,
      `I have run into this same issue before.`,
      `Before you switch to fake plants, try this.`,
      `You are not really a murderer...I hope!`,
    ],
    partTwo: [
      `If you are experiencing that, it sounds like a classic case of over watering. Try switching to once a week.`,
      `What you're experiencing sounds like too little water to me. Bump up the frequency of watering and it should start to revive.`,
      `Those require their roots to be nice and snug. Try repotting it in a smaller vessel.'`,
      `Sounds like maybe it needs a larger pot. These plants need more room to let their root system spread.`,
      `While it may seem counter intuitive, they actually can't handle full sun for long. It would do much better with indirect light.`,
      `I would position it somewhere that it gets partial sunlight.`,
      `Check to see if the leaves are dripping water. If so, it's just over watered and should be fine when you cut that back.`,
      `Sounds like too much water.`,
      `If the leaves are yellowing, but not brown around the edges, try watering less.`,
      `Check it for mites, maybe that's the cause?`,
      `Check your local plant shop for a good organic remedy.`,
      `Sounds like that one might be a lost cause.`,
      `You'll need to unpot it, rinse the root system, and cut off and dead roots. Then replant it with new soil and continue to monitor.`,
      `It's definitely overwater. Make sure to cut off the drooping leaves. Also, be careful... they smell like death.`,
      `In order for it to sprout, it'll ned 6 hours of direct light daily.`,
      `I would probably just give it less water.`,
      `You may need to split the plant, or get a much larger pot for it.`,
    ],
  },
};
