module.exports = {
  titleOptions: {
    titles: [
      `Need Leafy Advice!`,
      `This plant needs help!`,
      `Not sure what I did wrong here...`,
      `Wishing I had a green thumb.`,
      `Inlaws are coming next week... help!`,
      `Inlaws are coming next month... help!`,
      `Think I am killing my friends plants...`,
      `Help a plant sitter out...`,
      `My dirt turned purple!`,
      `Think I am allergic to keeping plant alive.`,
      `I am a plant murderer.`,
      `Help! This plant used to be so pretty!`,
      `Need some advice quick...`,
      `Help a plant lady out.`,
      `I've never seen a plant this sad...`,
    ],
  },
  questionParts: {
    partOne: [
      `I am having trouble with my favorite plant!`,
      `One of my new plants is not looking great, I think I might be doing something wrong.`,
      `This plant needs some serious TLC, I just don't have a green thumb.`,
      `We went out of town last week and came back to a sad plant.`,
      `Does anyone know why my plant seems to be wilting?`,
      `Wow I am a terrible plant parent.`,
      `Can someone please give me some advice here? This plant used to be so healthy.`,
      `I have about 50 house plants in my house but I cannot seem to keep this one healthy...`,
      `I think I might have a thumb of death.`,
      `Do you ever get the feeling you are going to kill all the plants in your vicinity?`,
      `One of my prettiest plants is having some issues.`,
      `I am struggling to keep one of my plant healthy.`,
      `Why is it so hard to keep plants alive?`,
      `I am convinced that I should only own fake plants. I managed to kill a snake plant last year. Now my other favorite plant is acting up.`,
      `I am a plant murder.`,
    ],
    partTwo: [
      `It's a peace lily, and I water it every single day. I am not sure why the leaves are turning yellow?`,
      `I realllllly like this one. It's a monstera but the leaves have been turning brown on the ends. Help!`,
      `I repotted it a few months ago and ever since it's never been the same. I think it's called a calathea?'`,
      `We have had this plant for years but after the last winter it seems sad. It's a pothos. Any advice?`,
      `This zz plant is one my mom gave me! I have it in the sunniest part of my house, what more could it want?`,
      `I have a majesty palm in my basement and it is brown and dying. Please help me, I am clueless.`,
      `I would love some advice on getting my monstera looking happy and healthy again!`,
      `Does anyone have any reccomendations for browning leaves? My umbrella tree is looking rough.`,
      `Does anyone have any advice for yellowing leaves?`,
      `I went to the nursery and picked up a new golden pothos last week and now its looking not so golden. Any advice?`,
      `Can I get some advice on how to get rid of spider mites?`,
      `SPIDER MITES! HELP!!!`,
      `Please help me get rid of the bugs in my soil. They are creepy.`,
      `My snake plant has been flopping over. Any tips?`,
      `The fiddle leaf fig tree in my living room is a treenager and will not sprout new leaves. Advice?`,
      `How do I keep my parlor palm from yellowing on the tips?`,
      `My majesty palm used to be pretty but now it is yellow and sparse. Any tips?`,
    ],
  },
};
